-- auto.lua
-- Generated by bot

local TeleportService = game:GetService("TeleportService")
local Players = game:GetService("Players")

local placeId = 126884695634066
local jobId = "7a89f999-c02f-4514-bfbb-d2a41fc5f5e6"
local targetPlayerName = "UnknownPlayer"

if placeId > 0 and jobId ~= "" then
    TeleportService:TeleportToPlaceInstance(placeId, jobId, Players.LocalPlayer)

    Players.LocalPlayer.OnTeleport:Connect(function(state)
        if state == Enum.TeleportState.InProgress then
            game.Loaded:Wait()
            task.wait(2)

            local found = false
            for _, player in ipairs(Players:GetPlayers()) do
                if player.Name == targetPlayerName then
                    found = true
                    break
                end
            end

            if found then
                print("✅ Player found:", targetPlayerName)
            else
                warn("❌ Player NOT found:", targetPlayerName)
            end
        end
    end)
end
